// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package GameProtocol

import "strconv"

type MessageType int8

const (
	MessageTypePlayerJoin MessageType = 0
	MessageTypePlayerMove MessageType = 1
	MessageTypeGameState  MessageType = 2
	MessageTypeHeartbeat  MessageType = 3
)

var EnumNamesMessageType = map[MessageType]string{
	MessageTypePlayerJoin: "PlayerJoin",
	MessageTypePlayerMove: "PlayerMove",
	MessageTypeGameState:  "GameState",
	MessageTypeHeartbeat:  "Heartbeat",
}

var EnumValuesMessageType = map[string]MessageType{
	"PlayerJoin": MessageTypePlayerJoin,
	"PlayerMove": MessageTypePlayerMove,
	"GameState":  MessageTypeGameState,
	"Heartbeat":  MessageTypeHeartbeat,
}

func (v MessageType) String() string {
	if s, ok := EnumNamesMessageType[v]; ok {
		return s
	}
	return "MessageType(" + strconv.FormatInt(int64(v), 10) + ")"
}
