// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package GameProtocol

import "strconv"

type PlayerCommandType int8

const (
	PlayerCommandTypeMoveUp    PlayerCommandType = 0
	PlayerCommandTypeMoveDown  PlayerCommandType = 1
	PlayerCommandTypeMoveLeft  PlayerCommandType = 2
	PlayerCommandTypeMoveRight PlayerCommandType = 3
)

var EnumNamesPlayerCommandType = map[PlayerCommandType]string{
	PlayerCommandTypeMoveUp:    "MoveUp",
	PlayerCommandTypeMoveDown:  "MoveDown",
	PlayerCommandTypeMoveLeft:  "MoveLeft",
	PlayerCommandTypeMoveRight: "MoveRight",
}

var EnumValuesPlayerCommandType = map[string]PlayerCommandType{
	"MoveUp":    PlayerCommandTypeMoveUp,
	"MoveDown":  PlayerCommandTypeMoveDown,
	"MoveLeft":  PlayerCommandTypeMoveLeft,
	"MoveRight": PlayerCommandTypeMoveRight,
}

func (v PlayerCommandType) String() string {
	if s, ok := EnumNamesPlayerCommandType[v]; ok {
		return s
	}
	return "PlayerCommandType(" + strconv.FormatInt(int64(v), 10) + ")"
}
